version: v1.0.0
loglevel: "info"
jwt_secret: "someverysecretkey"
admin_secret: "somesecretpassword"

api:
    port: 8080
    secret_key: ""
db:
    host: localhost
    port: 27017
    database: myprojects
    user: myprojects